# Generated by Django 3.2.5 on 2021-07-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='bruh_points',
        ),
    ]
